### ISSUE TITLE
Добавить проверки на потенцально возможные исключения

### ISSUE THREAD

**Issue by alexdany657** [m20-sch57/thetruehat#108]
Чтобы сервер не падал, даже, если сигналы отправлялись неправильно и т.д.

**Comment by lounres** [comment]
А почему этот тикет закрыт? Разве проверки реализованы?

**Comment by gtivansan** [comment]
Этот тикет закрыт, поскольку не описывает конкретную задачу, которую можно решить.
Новые возможные исключения будут появляться постоянно.

**Comment by lounres** [comment]
Частично не согласен: можно было бы поставить хотя бы банальные try-catch на отработки сигналов и т.п., чтобы сервер не падал. Но ладно, пусть закроется.
