### ISSUE TITLE
Proposal: Время ожиждания

### ISSUE THREAD

**Issue by alexdany657** [m20-sch57/thetruehat#112]
Предложение от клиента:
"Good game. I totally enjoyed it. To save even more time I would reduced 1-2-3 for just 1."

**Comment by lounres** [comment]
Это странное предложение: на деле не будет особой экономии времени. Можно, конечно, сделать настройки комнаты; но если это персональные настройки, то экономии не будет абсолютно.

**Comment by gtivansan** [comment]
Ну как не будет экономии? По ощущениям темп игры должен увеличиться.
Мы же будем делать настройку времени объяснения. Вот это тогда тоже сделаем.

**Comment by lounres** [comment]
> Ну как не будет экономии? По ощущениям темп игры должен увеличиться.
> Мы же будем делать настройку времени объяснения. Вот это тогда тоже сделаем.

@gtivansan, да, по ощущениям темп немного увеличится; а вот формально - нет (я и говорил про формальную сторону). Также повторюсь, что это обязательно надо делать пользовательской настройкой. Иначе проблем, что один хочет, а другой не хочет, не оберёмся.

**Comment by gtivansan** [comment]
А какая разница, что там формально происходит?
Про пользовательскую настройку не понимаю. Как это, у одного время идёт так, у другого эдак.

**Comment by alexdany657** [comment]
Я это вижу, как настройку игры (которая устанавливается хостом)

**Comment by lounres** [comment]
> А какая разница, что там формально происходит?

Какая разница? Да такая, что я опровергаю утверждение "To save even more time I would reduced 1-2-3 for just 1.", говоря, что это не поможет.

> Про пользовательскую настройку не понимаю. Как это, у одного время идёт так, у другого эдак.

Легко: у одного таймер засекается за три секунды и тикает три раза, а у другого - за секунду и тикает уже один раз.

**Comment by alexdany657** [comment]
Дело в том, что помимо этих 3 секунд есть еще и задержка на транспорт. И поэтому, кажется, что игра идет долго...

**Comment by lounres** [comment]
> Дело в том, что помимо этих 3 секунд есть еще и задержка на транспорт. И поэтому, кажется, что игра идет долго...

Это формальная составляющая, про которую я говорил.

**Comment by alexdany657** [comment]
Так нет же, люди пишут, что им не хочется ждать 4 секунды после того, как оба нажмут готов. Кажется, что можно сделать время ожидания настраиваем для игры так же, как и время объяснения.

**Comment by lounres** [comment]
Хорошо, если люди хотят побыстрее начать, то согласен. Просто если один хочет побыстрее, а второй хочет его 3 секунды, то тут либо личные настройки делать, либо пусть спорят, кто кому уступит.

**Comment by alexdany657** [comment]
Эта настройка, как и остальные, должны быть у хоста. Он их опрашивает и исходя из предпочтений принимает решение.
