### ISSUE TITLE
Придумать и осознать, какие ограничения на настройки нужны.

### ISSUE THREAD

**Issue by lounres** [m20-sch57/thetruehat#151]
10 часов для объяснения мы не потянем. Возможно, не хочется давать использовать все слова в игре (можем не потянуть). **Так какие условия мы хотим поставить?**

**Comment by gtivansan** [comment]
Я, вот, могу числа какие-нибудь ~~от балды~~ написать:
- Количество слов:  0 - 999
- Время  (0-99)+(0-999)+(0-99)

Я думаю, я смог попасть в интервал между "слишком много, мы не потянем" и "слишком мало, захотят больше".
