### ISSUE TITLE
Question: m20 or 11M

### ISSUE THREAD

**Issue by alexdany657** [m20-sch57/thetruehat#194]
Надо решить: **m20** или **11M**

**Comment by kuyanov** [comment]
Предлагаю ещё 2 опции: **11M (m20)** и **m20 (11M)**

**Comment by gtivansan** [comment]
[Результаты опроса](https://docs.google.com/spreadsheets/d/e/2PACX-1vToZmJGTAhXcGy_RIjnSSwfmPGt-fV0Q0qhsCLUoxOywd3KA8nV7za6WXQonLIEP5OndWs9E-xZ2tlB/pubchart?oid=234287953&format=interactive) который сделал Глеб

**Comment by lounres** [comment]
Больше [статистики](https://docs.google.com/spreadsheets/d/e/2PACX-1vToZmJGTAhXcGy_RIjnSSwfmPGt-fV0Q0qhsCLUoxOywd3KA8nV7za6WXQonLIEP5OndWs9E-xZ2tlB/pubchart?oid=541394602&format=interactive) богу статистики (что будет, если за ответы давать 2, 1, 0, -1 и -2).

**Comment by gtivansan** [comment]
Мне кажется, победил "m20". Баллов с "M20" равное кол-во, но по таким параметрам, как "очень нравится" и "абсолютно не нравится", "m20" опережает всех.

**Comment by kuyanov** [comment]
Ну а вариант 11М даже не рассматривали ((

**Comment by gtivansan** [comment]
Я так понимаю, вопрос закрыт.

**Comment by gtivansan** [comment]
Я так понимаю, вопрос закрыт.
