### ISSUE TITLE
Доперевести на английский всё

### ISSUE THREAD

**Issue by gtivansan** [m20-sch57/thetruehat#232]
![image](https://user-images.githubusercontent.com/43723504/85832654-2a8d3d00-b799-11ea-94a5-b0f2b664111a.png)
![image](https://user-images.githubusercontent.com/43723504/85832705-3a0c8600-b799-11ea-86d6-55883fe7792d.png)
![image](https://user-images.githubusercontent.com/43723504/85832748-4d1f5600-b799-11ea-8b9f-fa18bf59dfbf.png)

**Comment by cookiedoth** [comment]
Ещё название страницы "Шляпа" вне зависимости от языка
