### ISSUE TITLE
Если участие для игрока было последним, для него показывается через сколько ходов следующее участие

### ISSUE THREAD

**Issue by gtivansan** [m20-sch57/thetruehat#252]
Соотв. нужно, чтобы сервер отсылал расписание длиной в круг.

**Comment by lounres** [comment]
*Немного занудства.* Слово "круг" занято другим значением (в нём <img src="https://render.githubusercontent.com/render/math?math=n(n-1)"> ходов, а не <img src="https://render.githubusercontent.com/render/math?math=n">).

**Comment by gtivansan** [comment]
Ну я вроде это значение и имел в виду.

**Comment by lounres** [comment]
Ну тогда два вопроса-момента:
1. Зачем? Чтобы понять, через сколько ходов участие того или иного игрока нужно не более <img src="https://render.githubusercontent.com/render/math?math=2n"> ходов (а на деле чуточку меньше). Зачем для этого <img src="https://render.githubusercontent.com/render/math?math=n(n-1)"> просчитывать?
2. Саша точно не будет нравится (да и мне в принципе тоже), что мы просчитываем что-то более, чем линейное. Это тратит достаточно неконтролируемо много места и времени.

**Comment by gtivansan** [comment]
Хорошо справедливо. Главное, чтобы можно было выяснить для каждого человека, будет ли следующее участие и через сколько ходов.

**Comment by gtivansan** [comment]
Может быть даже стоит просто поддерживать конкретно эту информацию на сервере.
