### ISSUE TITLE
 Одинаковые имена

### ISSUE THREAD

**Issue by cookiedoth** [m20-sch57/thetruehat#27]
На данный момент никак не обрабатывается случай одинаковых имён игроков в комнате.

Это может привести к неоднозначностям при использовании функций игры, в которых игрок идентифицируется по имени.

Необходимо интерпретировать присоединение игрока с существующим именем как его переподключение (в случае, если этот игрок оффлайн), иначе не выполнять такие запросы.

**Comment by lounres** [comment]
Да, если я правильно помню, по последним договорённостям в комнате все ники должны быть разными (чтобы даже серверу не путаться, кто есть кто). Кажется, это продолжение #12.
