### ISSUE TITLE
Кнопки копирования ключа/ссылки есть только на одной странице

### ISSUE THREAD

**Issue by cookiedoth** [m20-sch57/thetruehat#28]
Эти кнопки могут облегчить распространение ключа комнаты среди её потенциальных участников. Однако, они присутствуют только на странице ввода имени. Мне кажется, что следует добавить их на страницу списка игроков, так как вполне вероятно, что хост сначала впишет своё имя, войдёт в комнату и только после этого начнёт распространять ключ/ссылку.

**Comment by lounres** [comment]
Соглашусь с замечанием Семёна. Лишь добавлю вот, что:
1. Важнее стройный дизайн, чем эти кнопки. Поэтому кнопки стоит вставлять, если получается их встроить в дизайн.
1. Возможно, стоит добавить не кнопки, а сделать так, что по нажатию на код, он копировался. (Как подстроить ссылку - не знаю. Просто предложение-идея.)
