### ISSUE TITLE
BUG: socket-server vulnerability

### ISSUE THREAD

**Issue by alexdany657** [m20-sch57/thetruehat#331]
После некоторых действий socket-server виснет (предположительно бесконечный цикл). Как воспроизвести (инструкция от @lounres, ветка `prod`):

1. Зайти вдвоём в любую **новую** (т.е. у которой не остались настройки от прошлой игры и тому подобное) комнату.
2. Поменять настройки:
    - Играть: заданное число кругов
    - Слова: загрузить, файл: [любой словарь на < 100 слов]
3. Начать игру.

Гипотеза (@lounres): хватает одновременно играть на круги и залить словарь меньше чем на константу, которая осталась в настройках комнаты (по умолчанию 100).

**Comment by kuyanov** [comment]
Заметил еще один косяк: если поставить "играть: заданное число кругов", то через 100 слов игра автоматически заканчивается
